[theme]
base = "light"
primaryColor = "#167568"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B42"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
