"use strict";
let DATA;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette=['#167568','#4875b8','#d08d32','#995798','#c45f65','#697f41','#778fa2','#a0a668'];
const state={page:'companies',sector:'전체 분야',comparison:'반도체',k:4,tab:'insights',company:'',peer:'',original:'',chapter:'',search:'',financeSector:'반도체',financeTab:'own',field:'반도체·AI 하드웨어',paperK:4,paperTab:'insights',paperSearch:'',paperPeriod:'전체 기간',paperId:''};
const option=(values,chosen)=>values.map(v=>`<option value="${esc(v)}" ${v===chosen?'selected':''}>${esc(v)}</option>`).join('');
const select=(id,label,values,value)=>`<label>${esc(label)}<select id="${id}">${option(values,value)}</select></label>`;
const note=s=>`<p class="note">${esc(s)}</p>`;
const link=(url,label='출처 원문')=>`<a class="source-link" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)} ↗</a>`;
const download=(name,label)=>`<a class="download" href="downloads/${esc(name)}.csv" download>${esc(label)}</a>`;
const metric=(label,value)=>`<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
const fmt=(n,d=2)=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:d,minimumFractionDigits:d});
function table(headers,rows,numeric=[]){return `<div class="table-scroll"><table><thead><tr>${headers.map((v,i)=>`<th class="${numeric.includes(i)?'numeric':''}">${esc(v)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>`<td class="${numeric.includes(i)?'numeric':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function chart(id,traces,extra={}){if(!$(id))return;Plotly.react(id,traces,{height:390,paper_bgcolor:'white',plot_bgcolor:'white',font:{family:'Arial, Malgun Gothic, sans-serif',size:12,color:'#47655d'},margin:{l:55,r:35,t:25,b:55},xaxis:{automargin:true,gridcolor:'#e6eeeb',zerolinecolor:'#c5d3cf'},yaxis:{automargin:true,gridcolor:'#e6eeeb',zerolinecolor:'#c5d3cf'},legend:{orientation:'h',y:1.12},...extra},{responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']});}
const chosenCompanies=()=>DATA.companies.filter(c=>state.sector==='전체 분야'||c.sector===state.sector);
const comparison=()=>DATA.comparisons[state.comparison];
const analysis=()=>comparison().variants[String(state.k)];
function tabs(items,current){return `<div class="tabs" role="tablist">${items.map(([key,label])=>`<button role="tab" aria-selected="${key===current}" class="${key===current?'selected':''}" data-tab="${key}">${label}</button>`).join('')}</div>`;}
function bindSelect(id,callback){$(id)?.addEventListener('change',e=>callback(e.target.value));}
function render(){state.page=location.hash.slice(1)||'companies';if(!['companies','papers','guide','workspace'].includes(state.page))state.page='companies';document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===state.page));if(state.page==='guide'){$('main').innerHTML=`<div class="eyebrow">ABOUT THIS PROJECT</div><article class="guide">${DATA.guide}</article>`;}else if(state.page==='workspace')renderWorkspace();else if(state.page==='papers')renderPapers();else renderCompanies();}
function renderCompanies(){
 const group=chosenCompanies();if(state.sector!=='전체 분야')state.comparison=state.sector;
 const comp=comparison();const max=Math.min(6,comp.companies.length-1);state.k=Math.max(2,Math.min(state.k,max));
 if(!comp.companies.includes(state.company))state.company=comp.companies[0];if(!group.some(c=>c.company===state.original))state.original=group[0].company;
 $('main').innerHTML=`<div class="eyebrow">01 / COMPANY ANALYSIS</div><h1>기업의 사업과 실적을 비교합니다</h1><p class="intro">같은 산업의 기업들이 무엇을 만드는지, 어떤 표현을 쓰는지, 매출과 영업이익이 어떻게 변했는지 살펴봅니다.</p><div class="notice">한국거래소 KIND · 2025년 결산 사업보고서 · 현재 수집본 22개 기업. <a href="#guide">처음 보는 분을 위한 설명 ↗</a></div><div class="controls">${select('sector','분석할 산업 분야',['전체 분야',...DATA.overview.sectors],state.sector)}${state.sector==='전체 분야'?select('comparison-sector','유사도·전략지도 비교 분야',DATA.overview.sectors,state.comparison):''}<label>자동 묶음 수 · <span id="k-value">${state.k}개</span><input id="k" type="range" min="2" max="${max}" value="${state.k}" aria-label="기업 자동 묶음 수"></label></div><div class="metrics">${metric('현재 범위의 분석 기업',`${group.length}개`)}${metric('같은 분야 유사도 비교',`${comp.companies.length}개`)}${metric('자동 묶음',`${new Set(analysis().labels).size}개`)}${metric('사업보고서 결산 연도','2025년')}</div>${note('산업 분야는 주된 사업을 기준으로 직접 지정했습니다. 유사도와 지도는 '+state.comparison+' 분야 안에서만 계산합니다. 자동 묶음은 산업 분류와 다른 탐색 결과입니다.')}${tabs([['insights','자사 기준 핵심 분석'],['overview','분야별 현황'],['finance','매출·영업이익'],['original','기업별 주력·전체 원문'],['map','전략 지도'],['similarity','기업 간 유사도'],['sources','데이터와 출처']],state.tab)}<div id="company-panel"></div><div id="company-comparison"></div>`;
 bindSelect('sector',value=>{state.sector=value;state.chapter='';state.search='';renderCompanies();});bindSelect('comparison-sector',value=>{state.comparison=value;state.k=Math.min(4,DATA.comparisons[value].companies.length-1);renderCompanies();});$('k').addEventListener('change',e=>{state.k=Number(e.target.value);renderCompanies();});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderCompanies();}));
 renderCompanyPanel();if(state.tab!=='insights')renderComparison();
}
function renderCompanyPanel(){
 const host=$('company-panel'),group=chosenCompanies(),a=analysis(),comp=comparison();
 if(state.tab==='insights'){renderCompanyInsights(host);
 }else if(state.tab==='overview'){
 host.innerHTML=`<section class="panel"><h2>몇 개 기업을 분석했나요?</h2><div id="company-counts" class="chart"></div>${note('전체 22개 기업을 분석했습니다. 선정한 표본 수이며 산업 전체의 기업 수나 시장 규모가 아닙니다.')}${table(['분야','분석 기업'],group.map(c=>[esc(c.sector),esc(c.company)]))}</section>${state.sector==='전체 분야'?'<section class="panel"><h2>분야별로 두드러지는 단어</h2><div id="overview-terms" class="chart"></div>'+note('기업별 단어 중요도의 분야 평균입니다. 같은 단어 점수표로 비교하며 색이 진할수록 평균 중요도가 높습니다. 매출이나 시장 점유율을 나타내지 않습니다.')+'</section>':''}`;
 chart('company-counts',[{type:'bar',orientation:'h',y:DATA.overview.sectors,x:DATA.overview.counts,text:DATA.overview.counts.map(n=>n+'개'),textposition:'outside',cliponaxis:false,marker:{color:palette[0]},hovertemplate:'%{y}: %{x}개<extra></extra>'}],{height:260,margin:{l:10,r:55,t:15,b:35},xaxis:{title:'분석 기업 수',range:[0,12],dtick:2},yaxis:{autorange:'reversed',automargin:true}});
 if(state.sector==='전체 분야')chart('overview-terms',[{type:'heatmap',x:DATA.overview.terms,y:DATA.overview.sectors,z:DATA.overview.profiles,colorscale:[[0,'#f0f7f4'],[1,palette[0]]],colorbar:{title:'평균 중요도'},hovertemplate:'%{y}<br>%{x}: %{z:.4f}<extra></extra>'}],{height:370,margin:{l:10,r:15,t:10,b:80},xaxis:{tickangle:-45,automargin:true},yaxis:{automargin:true}});
 }else if(state.tab==='finance')renderFinance(host);
 else if(state.tab==='original')renderOriginal(host);
 else if(state.tab==='map'){
 host.innerHTML=`<section class="panel"><h2>${esc(state.comparison)} · 기업 전략 지도</h2><div id="company-map" class="chart"></div>${note('점 하나는 기업 한 곳입니다. 가까운 점은 표현이 비슷한지 읽어볼 후보입니다. 두 축으로 압축한 설명 분산은 '+fmt(a.variance*100,1)+'%이며, 실제 유사도와 원문을 함께 확인하세요.')}${clusterList(a)}</section>`;drawMap('company-map',a,comp.companies);
 }else if(state.tab==='similarity'){
 host.innerHTML=`<section class="panel"><h2>${esc(state.comparison)} · 같은 분야 기업 간 유사도</h2><div id="company-similarity" class="chart"></div>${note('같은 분야 문서만으로 단어 중요도를 다시 계산했습니다. 1에 가까울수록 글의 표현이 비슷하며 실제 경쟁 관계나 기업의 성과를 증명하는 점수는 아닙니다.')}</section>`;
 chart('company-similarity',[{type:'heatmap',x:comp.companies,y:comp.companies,z:comp.similarity,zmin:0,zmax:1,colorscale:[[0,'#f0f7f4'],[1,palette[0]]],colorbar:{title:'유사도'},hovertemplate:'%{y} ↔ %{x}<br>유사도 %{z:.3f}<extra></extra>'}],{height:Math.max(420,comp.companies.length*45),margin:{l:10,r:10,t:10,b:95},xaxis:{tickangle:-45,automargin:true},yaxis:{autorange:'reversed',automargin:true}});
 }else{
 host.innerHTML=`<section class="panel"><h2>기업 데이터와 수집 기록</h2>${note('제공처: '+DATA.company_manifest.source+' · 분석 범위: II. 사업의 내용. 원문 표지의 기업명과 결산일을 확인했습니다. 고정 제출본이며 최신 정정 여부는 출처에서 확인하세요.')}${table(['기업','분야','결산 연도','분석한 절','수집 시점 (UTC)','원문'],group.map(c=>[esc(c.company),esc(c.sector),esc(c.fiscal_year),esc(c.section),esc(c.collected_at),link(c.source_url)]))}${download('companies','기업 원문·출처 CSV 다운로드')}${download('financials','매출·영업이익·원문 근거 CSV 다운로드')}${note('기본 수집본은 고정 자료입니다. 내 자료 분석 메뉴에서 기업 CSV 업로드와 새 논문 수집을 실행할 수 있습니다.')}</section>`;
 }
}
function clusterList(a){return `<div class="cluster-list">${Object.entries(a.keywords).map(([k,words])=>`<div><span class="pill">묶음 ${Number(k)+1}</span><span class="record">${words.map(esc).join(' · ')}</span></div>`).join('')}</div>`;}
function drawMap(id,a,names){const labels=[...new Set(a.labels)].sort((a,b)=>a-b);chart(id,labels.map(label=>{const ix=a.labels.map((v,i)=>v===label?i:-1).filter(i=>i>=0);return {type:'scatter',mode:'markers',name:'묶음 '+(label+1),x:ix.map(i=>a.coordinates[i][0]),y:ix.map(i=>a.coordinates[i][1]),text:ix.map(i=>names[i]),customdata:ix.map(()=>a.keywords[String(label)].join(', ')),marker:{size:13,color:palette[label%palette.length],line:{width:1,color:'white'}},hovertemplate:'%{text}<br>%{customdata}<extra></extra>'};}),{height:450,xaxis:{title:'SVD 축 1',automargin:true},yaxis:{title:'SVD 축 2',automargin:true}});}
function renderComparison(){
 const comp=comparison(),i=comp.companies.indexOf(state.company),peers=comp.companies.map((name,j)=>({name,j,score:comp.similarity[i][j]})).filter(p=>p.j!==i).sort((a,b)=>b.score-a.score).slice(0,3);
 if(!peers.some(p=>p.name===state.peer))state.peer=peers[0].name;const j=comp.companies.indexOf(state.peer),pair=comp.pairs[`${i}:${j}`];
 $('company-comparison').innerHTML=`<section class="panel"><h2>${esc(state.comparison)} · 기업별 원문 비교</h2><div class="controls">${select('compare-company','기업 선택',comp.companies,state.company)}${select('compare-peer','비교 기업',peers.map(p=>p.name),state.peer)}</div><div class="metrics">${peers.map(p=>metric(p.name,fmt(p.score,3))).join('')}</div><h3>공통 표현</h3><p>${pair.common.map(w=>`<span class="pill">${esc(w)}</span>`).join('')||'상위 공통 표현 없음'}</p><div class="two-column">${[[state.company,pair.left,pair.left_evidence],[state.peer,pair.right,pair.right_evidence]].map(([name,words,quotes])=>{const c=DATA.companies.find(c=>c.company===name);return `<div class="card"><h3>${esc(name)}</h3>${note('상대적으로 높은 표현: '+words.join(', '))}${quotes.map(q=>`<p class="quote">${esc(q)}</p>`).join('')}${link(c.source_url)}<p class="record">원문 ID ${esc(c.report_id)} · ${esc(c.section)} · 수집 ${esc(c.collected_at)}</p></div>`;}).join('')}</div>${note('표현의 유사도입니다. 주력 사업은 기업별 전체 원문의 제품·서비스 설명과 실적을 함께 읽어 확인하세요.')}</section>`;
 bindSelect('compare-company',v=>{state.company=v;renderComparison();});bindSelect('compare-peer',v=>{state.peer=v;renderComparison();});
}
function renderFinance(host){
 const available=state.sector==='전체 분야'?DATA.overview.sectors:[state.sector];if(!available.includes(state.financeSector))state.financeSector=available[0];const companies=chosenCompanies().filter(c=>c.sector===state.financeSector);const values=DATA.financials.filter(r=>companies.some(c=>c.company===r.company));
 host.innerHTML=`<section class="panel"><h2>매출과 영업이익 · 2023~2025년</h2>${note('매출은 기업이 벌어들인 금액, 영업이익은 주요 영업에서 수익과 비용을 계산한 이익입니다. 연결은 종속회사를 포함하고 별도는 해당 법인만 집계합니다. 기업 전체 실적이며 산업 사업부 매출과 다를 수 있습니다.')}<div class="controls">${select('finance-sector','재무 비교 산업 분야',available,state.financeSector)}${select('finance-mode','그래프 보기',['기업별 연도 변화','같은 분야 기업 간 비교'],state.financeTab==='own'?'기업별 연도 변화':'같은 분야 기업 간 비교')}</div><div id="finance-charts"></div>${note('단위: 억원. 원문에 있는 수치만 표시합니다. 틸론의 2023년 연결 요약 실적은 해당 공시에 없어 비워 둡니다. 코다코는 감사 의견거절이 있는 공시이므로 원문을 함께 확인하세요.')}${table(['기업','연도','매출액 (억원)','영업이익 (억원)','기준','출처'],companies.flatMap(c=>[2023,2024,2025].map(year=>{const rows=values.filter(r=>r.company===c.company&&Number(r.year)===year);if(!rows.length)return [esc(c.company),String(year),'자료 없음','자료 없음','연결 요약 미제공',link(c.source_url)];const rev=rows.find(r=>r.metric==='매출액'),profit=rows.find(r=>r.metric==='영업이익');return [esc(c.company),String(year),rev?fmt(Number(rev.value_krw)/1e8):'자료 없음',profit?fmt(Number(profit.value_krw)/1e8):'자료 없음',esc(rows[0].basis),link(c.source_url)];})),[1,2,3])}${download('financials','실적·단위·출처·원문 근거 CSV 다운로드')}</section>`;
 bindSelect('finance-sector',v=>{state.financeSector=v;renderFinance(host);});bindSelect('finance-mode',v=>{state.financeTab=v==='기업별 연도 변화'?'own':'compare';renderFinance(host);});
 if(state.financeTab==='own'){
 $('finance-charts').innerHTML=note('파란색: 매출액 · 초록색: 영업이익. 기업마다 세로축 범위가 다릅니다. 작은 그래프의 선 높이로 기업 간 규모를 비교하지 마세요.')+`<div class="two-column">${companies.map((c,i)=>`<div class="card"><h3>${esc(c.company)} · ${esc(values.find(r=>r.company===c.company)?.basis??'')}</h3><div id="finance-${i}" class="chart"></div></div>`).join('')}</div>`;
 companies.forEach((c,i)=>{const rows=values.filter(r=>r.company===c.company);chart(`finance-${i}`,['매출액','영업이익'].map((metric,i)=>{const data=rows.filter(r=>r.metric===metric).sort((a,b)=>Number(a.year)-Number(b.year));return {type:'scatter',mode:'lines+markers',name:metric,x:data.map(r=>Number(r.year)),y:data.map(r=>Number(r.value_krw)/1e8),marker:{color:metric==='매출액'?palette[1]:palette[0]},hovertemplate:'%{x}년<br>'+metric+' %{y:,.2f}억원<extra></extra>'};}),{height:265,showlegend:false,margin:{l:10,r:20,t:15,b:35},xaxis:{tickvals:[2023,2024,2025],tickformat:'d',automargin:true},yaxis:{tickformat:',.0f',nticks:5,automargin:true,gridcolor:'#e6eeeb'}});});
 }else{
 $('finance-charts').innerHTML=`<h3>${esc(state.financeSector)} · 2025년 같은 축 비교</h3><div id="revenue-compare" class="chart"></div><div id="profit-compare" class="chart"></div>`;
 ['매출액','영업이익'].forEach((metric,i)=>{const rows=values.filter(r=>r.metric===metric&&Number(r.year)===2025).sort((a,b)=>Number(a.value_krw)-Number(b.value_krw));chart(i===0?'revenue-compare':'profit-compare',[{type:'bar',orientation:'h',y:rows.map(r=>r.company+' ('+r.basis+')'),x:rows.map(r=>Number(r.value_krw)/1e8),marker:{color:i===0?palette[1]:palette[0]},hovertemplate:'%{y}<br>'+metric+' %{x:,.2f}억원<extra></extra>'}],{title:{text:'2025년 '+metric,x:0.01,font:{size:17}},height:Math.max(320,rows.length*42),margin:{l:10,r:35,t:55,b:35},xaxis:{title:'금액 (억원)',tickformat:',.0f',automargin:true},yaxis:{automargin:true}});});
 }
}
function renderOriginal(host){
 const group=chosenCompanies(),record=group.find(c=>c.company===state.original),chapters=[...new Set(record.sections.map(s=>s.chapter))];if(!chapters.includes(state.chapter)&&state.chapter!=='전체 항목')state.chapter=chapters.find(c=>c!=='사업의 내용')||chapters[0];
 host.innerHTML=`<section class="panel"><h2>기업별 사업 설명과 전체 원문</h2><div class="controls">${select('original-company','주력 사업과 원문을 볼 기업',group.map(c=>c.company),state.original)}</div><h3>${esc(record.company)} · ${esc(record.sector)}</h3>${link(record.source_url,record.company+' 사업보고서 원문')}${note('2025년 결산 · '+record.section+' · 수집 '+record.collected_at)}<h3>기업 사업 설명 · 원문 발췌</h3><div class="source-reader">${record.preview.map(p=>`<p>${esc(p)}</p>`).join('')}</div>${note('제품·서비스와 고객을 확인하고 주요 제품·연구개발 항목 및 매출·영업이익을 함께 읽어 주력 사업을 살펴보세요.')}<h3>전체 사업 내용 원문</h3><div class="controls">${select('original-chapter','원문 큰 항목',[...chapters,'전체 항목'],state.chapter)}<label>소제목·내용 검색<input id="original-search" type="search" placeholder="예: 유동성, 외화, 연구개발" value="${esc(state.search)}"></label></div>${note('소제목을 누르면 해당 문단과 표가 열립니다. 검색하면 전체 사업 절에서 찾습니다. 금액 표는 원래 통화·단위를 유지합니다.')}<div id="original-sections"></div></section>`;
 bindSelect('original-company',v=>{state.original=v;state.chapter='';state.search='';renderOriginal(host);});bindSelect('original-chapter',v=>{state.chapter=v;renderOriginalSections(record);});$('original-search').addEventListener('input',e=>{state.search=e.target.value;renderOriginalSections(record);});renderOriginalSections(record);
}
function renderOriginalSections(record){const query=state.search.trim().toLowerCase();const sections=record.sections.filter(s=>query?(s.title+' '+JSON.stringify(s.blocks)).toLowerCase().includes(query):state.chapter==='전체 항목'||s.chapter===state.chapter);$('original-sections').innerHTML=sections.map((s,i)=>`<details data-section="${i}"><summary>${esc(s.title)}</summary><div class="detail-body"></div></details>`).join('')||'<p class="empty">검색 조건에 맞는 원문 항목이 없습니다.</p>';$('original-sections').querySelectorAll('details').forEach(el=>el.addEventListener('toggle',()=>{if(el.open&&!el.dataset.loaded){el.querySelector('.detail-body').innerHTML=renderBlocks(sections[Number(el.dataset.section)].blocks);el.dataset.loaded='yes';}}));}
function renderBlocks(blocks){return `<div class="source-reader">${blocks.map(b=>{if(b.type==='heading')return `<h4>${esc(b.text)}</h4>`;if(b.type==='table')return (b.unit?note(b.unit):'')+(b.rows.length?table(b.columns,b.rows.map(row=>row.map(esc))):note(b.columns.join(' · ')));return `<p>${esc(b.text)}</p>`;}).join('')}</div>`;}
function renderPapers(){
 const field=DATA.papers[state.field],a=field.variants[String(state.paperK)];
 $('main').innerHTML=`<div class="eyebrow">02 / TECHNOLOGY PAPERS</div><h1>기술 분야별 연구를 살펴봅니다</h1><p class="intro">실제 논문의 제목과 초록을 비교해 비슷한 주제를 찾고, 같은 길이의 두 기간에서 단어 사용 비율이 어떻게 달라졌는지 확인합니다.</p><div class="notice">OpenAlex · arXiv 원문 링크와 초록이 있는 논문 · 수집본 2026.09.13. <a href="#guide">분석 방법을 쉽게 읽기 ↗</a></div><div class="controls">${select('paper-field','분석할 기술 분야',Object.keys(DATA.papers),state.field)}<label>자동 묶음 수 · ${state.paperK}개<input id="paper-k" type="range" min="2" max="8" value="${state.paperK}" aria-label="논문 자동 묶음 수"></label></div><div class="metrics">${metric('현재 분야 논문','120편')}${metric('2025년 1~8월','60편')}${metric('2026년 1~8월','60편')}${metric('전체 분야 표본 합계','480편')}</div>${note('분야 사이에 같은 논문이 포함될 수 있습니다. 최신순 제한 표본이며 날짜는 OpenAlex 출판일 기준입니다. PDF 전체를 분석한 결과가 아닙니다.')}${tabs([['insights','연구 내용과 시사점'],['map','주제 지도'],['change','두 기간 비교'],['cooccur','키워드 동시 출현'],['original','논문별 제목·초록'],['sources','데이터와 출처']],state.paperTab)}<div id="paper-panel"></div>`;
 bindSelect('paper-field',v=>{state.field=v;state.paperSearch='';state.paperId='';renderPapers();});$('paper-k').addEventListener('change',e=>{state.paperK=Number(e.target.value);renderPapers();});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.paperTab=b.dataset.tab;renderPapers();}));renderPaperPanel();
}
function renderPaperPanel(){const field=DATA.papers[state.field],a=field.variants[String(state.paperK)],host=$('paper-panel');
 if(state.paperTab==='insights'){renderResearchInsights(host);
 }else if(state.paperTab==='map'){
 host.innerHTML=`<section class="panel"><h2>${esc(state.field)} · 논문 주제 지도</h2><div id="paper-map" class="chart"></div>${note('점 하나는 논문 한 편이며 색은 자동 묶음입니다. 압축된 설명 분산 '+fmt(a.variance*100,1)+'%. 지도에서 가까운 논문도 제목·초록을 읽어 확인하세요.')}${clusterList(a)}</section><section class="panel"><h2>자동 묶음별 대표 논문</h2>${Object.entries(a.representatives).map(([label,ix])=>`<h3>묶음 ${Number(label)+1} · ${a.keywords[label].map(esc).join(', ')}</h3>${ix.map(i=>paperDetail(field.records[i])).join('')}`).join('')}</section>`;drawMap('paper-map',a,field.records.map(r=>r.title));
 }else if(state.paperTab==='change'){
 const changes=field.changes;host.innerHTML=`<section class="panel"><h2>두 기간의 단어 등장 비율 변화</h2>${note('한 논문에서 단어를 여러 번 써도 한 편으로 셉니다. 2026년 비율에서 2025년 비율을 뺀 값이며 단위는 %p입니다. 두 기간 합계 4편 이상에서 등장한 단어 중 변화가 큰 단어를 표시합니다.')}<div id="paper-changes" class="chart"></div>${table(['단어','2025년 논문 수 / 60','2025년 비율','2026년 논문 수 / 60','2026년 비율','변화 (%p)'],changes.map(r=>[esc(r.term),String(r.previous_n),fmt(r.previous*100,1)+'%',String(r.recent_n),fmt(r.recent*100,1)+'%',(r.change>0?'+':'')+fmt(r.change,1)]),[1,2,3,4,5])}${note('2025년·2026년 각각 1~8월의 최신순 60편 표본입니다. 산업 전체의 유행이나 연구량 증가를 확정하는 수치는 아닙니다.')}</section><section class="panel"><h2>자동 주제 묶음별 표본 비중</h2><div id="paper-shares" class="chart"></div>${note('각 기간의 60편 중 현재 자동 묶음에 속한 논문의 비율입니다. 묶음 수를 바꾸면 분류와 비중이 달라집니다.')}</section>`;
 const top=changes.slice(0,20).reverse();chart('paper-changes',[{type:'bar',orientation:'h',y:top.map(r=>r.term),x:top.map(r=>r.change),marker:{color:top.map(r=>r.change>=0?palette[0]:palette[1])},hovertemplate:'%{y}<br>변화 %{x:+.1f}%p<extra></extra>'}],{height:Math.max(420,top.length*29),margin:{l:10,r:35,t:15,b:45},xaxis:{title:'최근 − 이전 (%p)',automargin:true,zeroline:true,zerolinecolor:'#93b1a7'},yaxis:{automargin:true}});
 const periods=[...new Set(a.shares.map(r=>r.period))];chart('paper-shares',periods.map((period,i)=>{const rows=a.shares.filter(r=>r.period===period);return {type:'bar',name:period,x:rows.map(r=>'묶음 '+r.cluster),y:rows.map(r=>r.share*100),marker:{color:palette[i===0?1:0]},customdata:rows.map(r=>r.count),hovertemplate:'%{x}<br>%{y:.1f}% (%{customdata}편)<extra></extra>'};}),{barmode:'group',height:340,yaxis:{title:'표본 비중 (%)',range:[0,100],automargin:true}});
 }else if(state.paperTab==='cooccur'){
 const edges=field.edges;host.innerHTML=`<section class="panel"><h2>같은 논문에서 함께 등장한 단어</h2>${note('상위 16개 단어 가운데 두 단어가 동시에 등장한 논문 수입니다. 2편 이상에서 함께 나온 쌍을 많은 순으로 최대 45개 표시합니다. 두 단어의 관계나 인과관계를 증명하지 않습니다.')}<div id="paper-edges" class="chart"></div>${table(['키워드 A','키워드 B','동시 등장 논문 수'],edges.map(r=>[esc(r.keyword_a),esc(r.keyword_b),String(r.documents)]),[2])}</section>`;const top=edges.slice(0,15).reverse();chart('paper-edges',[{type:'bar',orientation:'h',y:top.map(r=>r.keyword_a+' + '+r.keyword_b),x:top.map(r=>r.documents),marker:{color:palette[0]},hovertemplate:'%{y}<br>%{x}편에서 동시 등장<extra></extra>'}],{height:510,margin:{l:10,r:35,t:15,b:40},xaxis:{title:'논문 수',automargin:true},yaxis:{automargin:true}});
 }else if(state.paperTab==='original'){
 host.innerHTML=`<section class="panel"><h2>${esc(state.field)} · 논문별 제목과 전체 초록</h2><div class="controls"><label>제목·초록 검색<input id="paper-search" type="search" value="${esc(state.paperSearch)}" placeholder="관심 기술 단어"></label>${select('paper-period','논문 기간',['전체 기간','2025년 1~8월','2026년 1~8월'],state.paperPeriod)}</div><div id="paper-originals"></div></section>`;$('paper-search').addEventListener('input',e=>{state.paperSearch=e.target.value;renderPaperOriginals(field);});bindSelect('paper-period',v=>{state.paperPeriod=v;renderPaperOriginals(field);});renderPaperOriginals(field);
 }else{
 const m=field.manifest;host.innerHTML=`<section class="panel"><h2>${esc(state.field)} · 데이터와 수집 기록</h2><p>제공처: ${esc(m.source)}</p><p>수집 검색 조건: ${esc(m.query)}</p>${table(['비교 기간','시작일','종료일','수집 시점 (UTC)','검색 일치 수','분석 표본 수'],m.periods.map(r=>[esc(r.period),esc(r.start_date),esc(r.end_date),esc(r.collected_at),String(r.total_matches),String(r.retained)]),[4,5])}${note('검색 결과 전체를 분석한 것이 아닙니다. 기간별 최신순 검색 결과 중 처음 200건에서 원문 링크와 초록 조건을 확인해 60편을 선정했습니다. 반도체·AI 하드웨어 분야는 제목·초록에 칩·하드웨어 관련 표현이 있는지도 확인했습니다.')}${download(field.dataset,'논문 제목·초록·출처 CSV 다운로드')}${table(['논문 제목','기간','OpenAlex 출판일','논문 원문','OpenAlex 정보'],field.records.map(r=>[esc(r.title),esc(r.period),esc(r.published),link(r.source_url,'arXiv'),link(r.metadata_url,'OpenAlex')]))}${note('수집 시각은 UTC입니다. OpenAlex 출판일은 arXiv 최초 제출일과 다를 수 있습니다. 현재 수집본의 결과이며 최신 자료를 자동으로 가져오는 화면은 아닙니다.')}</section>`;
 }
}
function paperDetail(r){return `<details><summary>${esc(r.title)}</summary><div class="detail-body"><p class="record">${esc(r.period)} · OpenAlex 출판일 ${esc(r.published)} · ${esc(r.authors)}</p><div class="source-reader"><p>${esc(r.abstract)}</p></div>${link(r.source_url,'arXiv 원문')} ${link(r.metadata_url,'OpenAlex 정보')}<p class="record">수집 시점 ${esc(r.collected_at)} · 논문 ID ${esc(r.paper_id)}</p></div></details>`;}
function renderPaperOriginals(field){const q=state.paperSearch.toLowerCase();const rows=field.records.filter(r=>(state.paperPeriod==='전체 기간'||r.period===state.paperPeriod)&&(!q||(r.title+' '+r.abstract).toLowerCase().includes(q)));$('paper-originals').innerHTML=note('조건에 맞는 논문 '+rows.length+'편. 제목을 누르면 전체 초록과 원문 출처가 열립니다.')+rows.map(paperDetail).join('');}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
fetch('data.json').then(r=>{if(!r.ok)throw new Error('Data response '+r.status);return r.json();}).then(data=>{DATA=data;render();}).catch(error=>{$('main').innerHTML='<h1>자료를 불러오지 못했습니다</h1><p>페이지를 새로고침해 주세요. 문제가 계속되면 GitHub의 데이터와 설명을 확인할 수 있습니다.</p><a href="https://github.com/jcpaix/mot-analytics">GitHub 프로젝트 ↗</a>';console.error(error);});
