function renderCompanyInsights(host){
 const names=comparison().companies;if(!names.includes(state.company))state.company=names[0];
 const b=MotInsights.benchmark(DATA,state.company),f=b.own,now=f.latest,prev=f.previous;
 const sign=n=>n>0?'+':'';const percent=n=>n===null?'자료 부족':sign(n)+fmt(n,1)+'%';const points=n=>n===null?'자료 부족':sign(n)+fmt(n,1)+'%p';
 const money=n=>n===null?'자료 없음':fmt(n/1e8)+'억원';
 const grow=f.growth===null?'같은 기준의 전년도 매출이 없어 성장률을 계산하지 않았습니다.':`매출은 ${money(prev.revenue)}에서 ${money(now.revenue)}으로 ${f.growth>=0?'증가':'감소'}했습니다. 전년 대비 변화는 ${percent(f.growth)}입니다.`;
 const profit=now.profit===null?'현재 영업이익 자료가 없습니다.':`2025년 영업${now.profit<0?'손실':'이익'}은 ${money(Math.abs(now.profit))}입니다. ${f.profitChange}. ${now.margin===null?'':`매출 100원당 영업 단계에서 ${fmt(Math.abs(now.margin),1)}원의 ${now.margin<0?'손실':'이익'}을 기록했습니다.`}`;
 const peer=now.audit?`${f.company.company}의 공시에 감사 관련 주의 사항(${now.audit})이 있어 비교 수치의 해석에 특히 주의해야 합니다.`:b.marginMedian===null?'같은 분야·같은 연결/별도 기준의 다른 기업에 비교 가능한 이익률 자료가 없습니다.':`자사를 제외한 ${now.basis} 기준 동종 표본 ${b.marginN}개사의 영업이익률 중앙값은 ${fmt(b.marginMedian,1)}%입니다. 자사는 ${now.margin===null?'이익률을 계산할 수 없습니다.':`${points(now.margin-b.marginMedian)} ${now.margin>=b.marginMedian?'높습니다':'낮습니다'}.`}`;
 const searchTerms=f.growth!==null&&f.growth<0?['주요 제품','판매','수주','가격']:now.profit<0?['원가','연구개발','판매비','비용']:['주요 제품','가격','생산능력','연구개발'];
 host.innerHTML=`<section class="panel"><div class="eyebrow">숫자 → 해석 → 확인할 원문</div><h2>자사를 기준으로 무엇이 달라졌나요?</h2><div class="controls">${select('insight-company','자사로 볼 기업',names,state.company)}</div>${note('선택한 기업을 중심으로 같은 산업 안에서 비교합니다. 회사 전체 실적이므로 해당 분야 사업부만의 성과와는 다를 수 있습니다.')}<div class="metrics">${metric('2025년 매출',money(now.revenue))}${metric('전년 대비 매출 성장률',percent(f.growth))}${metric('2025년 영업이익률',now.margin===null?'자료 부족':fmt(now.margin,1)+'%')}${metric('전년 대비 이익률 변화',points(f.marginDelta))}</div><div class="insight-stack"><article><span class="pill">확인한 사실 · 매출</span><p>${esc(grow)}</p></article><article><span class="pill">확인한 사실 · 수익성</span><p>${esc(profit)}</p></article><article><span class="pill">비교 조건 · ${esc(now.basis||'기준 미확인')}</span><p>${esc(peer)}</p></article></div>${link(now.source,'계산에 사용한 사업보고서')}<details><summary>계산식과 비교 대상 확인</summary><div class="detail-body"><p>매출 성장률 = (2025년 매출 ÷ 2024년 매출 − 1) × 100. 전년도 매출이 0 이하이거나 자료·연결 기준이 다르면 계산하지 않습니다.</p><p>영업이익률 = 영업이익 ÷ 매출 × 100. 이익률 변화는 두 연도의 차이(%p)입니다. 전년도 손실을 나눠 만든 영업이익 성장률은 쓰지 않고 흑자·적자 전환과 금액 차이를 표시합니다.</p><p>비교 대상은 같은 분야, 같은 연결·별도 기준, 감사 관련 주의 사항이 없는 다른 기업입니다. 중앙값은 그 수치를 크기순으로 정렬했을 때 가운데 값이며 자사는 제외합니다.</p><p>포함: ${esc(b.peers.map(p=>p.company.company).join(', ')||'없음')}.</p><p>제외: ${esc(b.excluded.map(p=>p.company+' ('+p.reason+')').join(', ')||'없음')}.</p></div></details></section><section class="panel"><h2>성장과 수익성을 함께 비교</h2><div id="position-map" class="chart"></div>${note('가로축은 전년 대비 매출 성장률, 세로축은 영업이익률입니다. 오른쪽일수록 매출 증가, 위쪽일수록 매출 대비 영업이익이 큽니다. 0 아래는 영업손실입니다. 점의 위치는 투자 순위가 아닙니다. 같은 기준의 선정 표본만 비교합니다.')}${table(['기업','재무 기준','매출 성장률','영업이익률','영업이익 변화','원문'],[f,...b.peers].map(p=>[esc(p.company.company)+(p.company.company===state.company?' (자사)':''),esc(p.latest.basis||'자료 없음'),percent(p.growth),p.latest.margin===null?'자료 부족':fmt(p.latest.margin,1)+'%',esc(p.profitChange),link(p.latest.source)]),[2,3])}</section><section class="panel"><h2>이 결과를 보고 다음에 확인할 것</h2><p>위 숫자는 변화가 있었다는 사실을 보여줍니다. 원인을 확인하려면 제품·가격·판매량·비용에 관한 원문을 읽어야 합니다.</p><div class="two-column"><article class="card"><h3>사업 내용과 연결해서 읽기</h3><p>${esc(f.growth!==null&&f.growth<0?'매출 감소가 판매량·판매가격·사업 매각 중 무엇과 관련되는지 제품별 매출과 판매 항목을 확인하세요.':now.profit<0?'매출 규모와 별개로 영업손실이 발생했습니다. 원가·연구개발·판매비의 설명과 일회성 비용 여부를 확인하세요.':'매출 증가와 이익률 변화가 함께 나타나는지 확인하고 제품 구성·판매가격·원가 설명을 대조하세요.')}</p><button class="action-button" id="read-own-source">${esc(f.company.company)}의 전체 사업 원문 읽기</button><p class="record">원문에서 찾아볼 표현: ${searchTerms.map(esc).join(' · ')}</p></article><article class="card"><h3>비교에서 바로 결론 내릴 수 없는 것</h3><p>같은 산업이라도 제품·고객·기업 규모가 다릅니다. 연결·별도 기준을 맞춰도 자회사 범위와 회계상 재작성은 다를 수 있습니다. 높은 유사도나 이익률만으로 경쟁력·투자 가치를 확정하지 않습니다.</p>${link(f.company.source_url,'원래 사업보고서 확인')}</article></div></section>`;
 bindSelect('insight-company',v=>{state.company=v;renderCompanyInsights(host);});$('read-own-source').addEventListener('click',()=>{state.original=state.company;state.tab='original';state.chapter='';state.search='';renderCompanies();$('company-panel').scrollIntoView({block:'start'});});
 const plotted=[...b.peers,f].filter(p=>p.growth!==null&&p.latest.margin!==null);
 chart('position-map',plotted.map(p=>({type:'scatter',mode:'markers',name:p.company.company,x:[p.growth],y:[p.latest.margin],marker:{size:p.company.company===state.company?19:12,color:p.company.company===state.company?palette[1]:palette[0],line:{color:'white',width:2}},hovertemplate:esc(p.company.company)+'<br>매출 성장률 %{x:.1f}%<br>영업이익률 %{y:.1f}%<extra></extra>'})),{height:400,showlegend:true,xaxis:{title:'매출 성장률 (%)',zeroline:true,zerolinecolor:'#8ba59e',automargin:true},yaxis:{title:'영업이익률 (%)',zeroline:true,zerolinecolor:'#8ba59e',automargin:true}});
}
function renderResearchInsights(host,fieldOverride=null){
 const field=fieldOverride||DATA.papers[state.field],trends=MotInsights.conceptTrends(state.field,field.records),top=trends.filter(t=>t.records.length>0).slice(0,3);
 host.innerHTML=`<section class="panel"><div class="eyebrow">기술 항목 → 변화 → 논문 근거</div><h2>어떤 연구 내용을 더 읽어볼까요?</h2>${note('제목과 초록에서 기술 항목별 용어를 찾아, 그 항목을 한 번 이상 언급한 논문의 비율을 비교합니다. 공개된 용어 목록을 사용한 규칙 기반 분류이며 하나의 논문이 여러 항목에 포함될 수 있습니다.')}<div id="concept-chart" class="chart"></div>${note('막대는 각 기간 표본 안의 언급 비율입니다. 변화는 최근 비율 − 이전 비율(%p)이며, 전체 연구량 증가나 기업 매출 기회를 의미하지 않습니다.')}<div class="insight-stack">${top.map(t=>`<article><span class="pill">${esc(t.label)}</span><h3>${fmt(t.rates[0],1)}% → ${fmt(t.rates[1],1)}% · ${t.change>0?'+':''}${fmt(t.change,1)}%p</h3><p>${esc(t.meaning)}</p><p>${esc(t.periods[0])} ${t.totals[0]}편 중 ${t.counts[0]}편, ${esc(t.periods[1])} ${t.totals[1]}편에서 언급했습니다.</p><p><strong>읽을 때 확인할 점:</strong> ${esc(t.question)}</p><details><summary>이 항목이 등장한 논문 ${t.records.length}편과 초록 보기</summary><div class="detail-body">${t.records.map(paperDetail).join('')}</div></details></article>`).join('')}</div></section><section class="panel"><h2>전체 기술 항목과 판정 근거</h2>${table(['기술 항목','뜻','이전 논문 수','최근 논문 수','비율 변화 (%p)'],trends.map(t=>[esc(t.label),esc(t.meaning),t.counts[0]+' / '+t.totals[0],t.counts[1]+' / '+t.totals[1],(t.change>0?'+':'')+fmt(t.change,1)]),[2,3,4])}<details><summary>어떤 단어가 있으면 해당 기술로 세나요?</summary><div class="detail-body">${table(['기술 항목','검색한 용어 패턴'],trends.map(t=>[esc(t.label),esc(t.pattern)]))}<p>제목과 초록을 대상으로 대소문자를 구분하지 않고 단어 경계에 맞춰 검색합니다. 표는 분석 조건이며 논문에서 사용하는 모든 동의어를 포함하지는 않습니다. 단순 언급만으로 그 논문의 핵심 기여라고 판단하지 않습니다.</p></div></details></section>`;
 if(trends.length){const periods=trends[0].periods;chart('concept-chart',periods.map((p,i)=>({type:'bar',orientation:'h',name:p,y:trends.map(t=>t.label),x:trends.map(t=>t.rates[i]),customdata:trends.map(t=>t.counts[i]),marker:{color:palette[i===0?1:0]},hovertemplate:'%{y}<br>%{x:.1f}% (%{customdata}편)<extra></extra>'})),{height:Math.max(380,trends.length*55),barmode:'group',margin:{l:10,r:30,t:40,b:45},xaxis:{title:'해당 기술을 언급한 논문 비율 (%)',range:[0,100],automargin:true},yaxis:{autorange:'reversed',automargin:true}});}
}
